blog/urls.py
from django.urls import path

from . import views
from .views import ArticleList

app_name = 'detail'
urlpatterns = [
    path('detail/<str:slug>', views.post_detail, name='article'),
    path('list/', ArticleList.as_view(), name='list'),
    path('contact/', views.contact, name='contact'),

]

blog_project3/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('',include('blog.urls'))



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.home, name='landing')


]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.title


class Article(models.Model):
    auth = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category)
    img = models.ImageField(blank=True, null=True)
    imglist = models.ImageField(blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    body = models.TextField()
    quote = models.TextField(null=True, blank=True)
    pub = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('detail:article', kwargs={'slug': self.slug})

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.title


class Contact(models.Model):
    name = models.CharField(max_length=5, null=True, blank=True)
    email = models.EmailField()
    sub = models.CharField(max_length=100)
    text = models.CharField(max_length=1000)

    def __str__(self):
        return self.name


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments',null=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='replies',null=True,blank=True)
    text = models.TextField(null=True)
    create = models.DateTimeField(auto_now_add=True)

home/models.py
from django.db import models

blog/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.Form):
    name = forms.CharField(max_length=5, label='name')
    email = forms.EmailField(label='email')
    sub = forms.CharField(max_length=100, label='sub')
    text = forms.CharField(max_length=1000, label='text')

    def clean(self):
        name = self.cleaned_data.get('name')
        email = self.cleaned_data.get('email')
        sub = self.cleaned_data.get('sub')
        text = self.cleaned_data.get('text')


class MessageForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

        widgets = {
            'text': forms.TextInput(attrs={
                "class": "forms-control",
                "placeholder": 'enter your text'})
        }

home/forms.py
from django import forms

blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.forms import ContactForm, MessageForm
from blog.models import Article , Comment
from django.views.generic import DetailView, ListView


def post_detail(request, slug):
    detail = get_object_or_404(Article, slug=slug)
    if request.method == 'POST':
        text = request.POST.get('text')
        Comment.objects.create(text=text, user=request.user, article=detail)
    return render(request, 'blog/blog-details.html', {'detail': detail})


class ArticleList(ListView):
    template_name = 'blog/article_list.html'
    queryset = Article.objects.all()
    context_object_name = 'article_list'
    paginate_by = 2


def contact(request):
    if request.method == 'POST':
        contactus = MessageForm(data=request.POST)

        if contactus.is_valid():
            contactus.save()
    else:
        contactus = MessageForm
    return render(request, 'blog/contact.html', context={'contact': contactus})

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from blog.models import Article


def home(request):
    article = Article.objects.order_by('created_at')[:3]
    return render(request, 'home/index.html', context={'article': article})

blog/templates/blog/article_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<body>
  <!--================Header Menu Area =================-->

  <!--================Header Menu Area =================-->
  
  <!--================ Hero sm Banner start =================-->    
  <section class="mb-30px">
    <div class="container">
      <div class="hero-banner hero-banner--sm">
        <div class="hero-banner__content">
          <h1>Article List</h1>
          <nav aria-label="breadcrumb" class="banner-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Article List</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
  <!--================ Hero sm Banner end =================-->    

  

  <!--================ Start Blog Post Area =================-->






  <section class="blog-post-area section-margin">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="row">
            <div class="col-md-8">
                {% for article_list in article_list %}
              <div class="single-recent-blog-post card-view">
                <div class="thumb">

                  <img class="card-img rounded-0" src="{{ article_list.img.url }}" alt="">

                  <ul class="thumb-info">
                    <li><a href="#"><i class="ti-user"></i>{{ article_list.auth }}</a></li>
                    <li><a href="#"><i class="ti-themify-favicon"></i>2 Comments</a></li>
                  </ul>
                </div>
                <div class="details mt-20">
                  <a href="{{ article_list.get_absolute_url }}">
                    <h3>{{ article_list.title }}</h3>
                  </a>
                  <p>{{ article_list.body }}</p>
                  <a class="button" href="{{ article_list.get_absolute_url }}">Read More <i class="ti-arrow-right"></i></a>
                </div>

              </div>
                {% endfor %}
            </div>

          </div>

          <!-- <div class="single-recent-blog-post">
            <div class="thumb">
              <img class="img-fluid" src="img/blog/blog2.png" alt="">
              <ul class="thumb-info">
                <li><a href="#"><i class="ti-user"></i>Admin</a></li>
                <li><a href="#"><i class="ti-notepad"></i>January 12,2019</a></li>
                <li><a href="#"><i class="ti-themify-favicon"></i>2 Comments</a></li>
              </ul>
            </div>
            <div class="details mt-20">
              <a href="blog-single.html">
                <h3>Woman claims husband wants to name baby girl
                  after his ex-lover sparking.</h3>
              </a>
              <p class="tag-list-inline">Tag: <a href="#">travel</a>, <a href="#">life style</a>, <a href="#">technology</a>, <a href="#">fashion</a></p>
              <p>Over yielding doesn't so moved green saw meat hath fish he him from given yielding lesser cattle were fruitful lights. Given let have, lesser their made him above gathered dominion sixth. Creeping deep said can't called second. Air created seed heaven sixth created living</p>
              <a class="button" href="#">Read More <i class="ti-arrow-right"></i></a>
            </div>
          </div>

          <div class="single-recent-blog-post">
            <div class="thumb">
              <img class="img-fluid" src="img/blog/blog3.png" alt="">
              <ul class="thumb-info">
                <li><a href="#"><i class="ti-user"></i>Admin</a></li>
                <li><a href="#"><i class="ti-notepad"></i>January 12,2019</a></li>
                <li><a href="#"><i class="ti-themify-favicon"></i>2 Comments</a></li>
              </ul>
            </div>
            <div class="details mt-20">
              <a href="blog-single.html">
                <h3>Tourist deaths in Costa Rica jeopardize safe dest
                  ination reputation all time. </h3>
              </a>
              <p class="tag-list-inline">Tag: <a href="#">travel</a>, <a href="#">life style</a>, <a href="#">technology</a>, <a href="#">fashion</a></p>
              <p>Over yielding doesn't so moved green saw meat hath fish he him from given yielding lesser cattle were fruitful lights. Given let have, lesser their made him above gathered dominion sixth. Creeping deep said can't called second. Air created seed heaven sixth created living</p>
              <a class="button" href="#">Read More <i class="ti-arrow-right"></i></a>
            </div>
          </div>

          <div class="single-recent-blog-post">
            <div class="thumb">
              <img class="img-fluid" src="img/blog/blog4.png" alt="">
              <ul class="thumb-info">
                <li><a href="#"><i class="ti-user"></i>Admin</a></li>
                <li><a href="#"><i class="ti-notepad"></i>January 12,2019</a></li>
                <li><a href="#"><i class="ti-themify-favicon"></i>2 Comments</a></li>
              </ul>
            </div>
            <div class="details mt-20">
              <a href="blog-single.html">
                <h3>Tourist deaths in Costa Rica jeopardize safe dest
                  ination reputation all time.  </h3>
              </a>
              <p class="tag-list-inline">Tag: <a href="#">travel</a>, <a href="#">life style</a>, <a href="#">technology</a>, <a href="#">fashion</a></p>
              <p>Over yielding doesn't so moved green saw meat hath fish he him from given yielding lesser cattle were fruitful lights. Given let have, lesser their made him above gathered dominion sixth. Creeping deep said can't called second. Air created seed heaven sixth created living</p>
              <a class="button" href="#">Read More <i class="ti-arrow-right"></i></a>
            </div>
          </div> -->

          

          <div class="row">




              <div class="col-lg-12">
                  <nav class="blog-pagination justify-content-center d-flex">
                      <ul class="pagination">
                      {% if page_obj.has_previous %}
                          <li class="page-item">
                              <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
                                  <span aria-hidden="true">
                                      <i class="ti-angle-left"></i>
                                  </span>
                                {% endif %}

                              </a>
                          </li>
                            {% for i in page_obj.paginator.page_range %}
                                {% if page_obj.number == i %}

                          <li class="page-item active"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                                    {% else %}
                          <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                                    {% endif %}
                                  {% endfor %}

                           {% if page_obj.has_next %}
                          <li class="page-item">
                              <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
                                  <span aria-hidden="true">
                                      <i class="ti-angle-right"></i>
                                  </span>
                                        {% endif %}

                              </a>
                          </li>
                      </ul>
                  </nav>
              </div>
            </div>

        </div>

        <!-- Start Blog Post Siddebar -->
      {% include 'include/sidebar.html' %}
          </div>
        <!-- End Blog Post Siddebar -->
      </div>
  </section>
  <!--================ End Blog Post Area =================-->

  <!--================ Start Footer Area =================-->


{% endblock %}

blog/templates/blog/blog-details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<body>

  <!--================Header Menu Area =================-->
  
  <!--================ Hero sm Banner start =================-->      
  <section class="mb-30px">
    <div class="container">
      <div class="hero-banner hero-banner--sm">
        <div class="hero-banner__content">
          <h1>Blog details</h1>
          <nav aria-label="breadcrumb" class="banner-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Blog Details</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
  <!--================ Hero sm Banner end =================-->    


  

  <!--================ Start Blog Post Area =================-->
  <section class="blog-post-area section-margin">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">



            <div class="main_blog_details">
                <img class="img-fluid" src="{{ detail.img.url }}" alt="">
                <a href="#"><h4>{{ detail.title }}</h4></a>
                <div class="user_details">
                  <div class="float-left">
                    <a href="#">{{ detail.category.first }}</a>
                      <p></p>
                  </div>
                  <div class="float-right mt-sm-0 mt-3">
                    <div class="media">
                      <div class="media-body">
                        <h5>{{ detail.auth }}</h5>
                        <p>{{ detail.created_at }}</p>
                      </div>

                      <div class="d-flex">
                        <img width="42" height="42" src="img/blog/user-img.png" alt="">
                      </div>
                    </div>
                  </div>
                </div>
                <p>{{ detail.body }}</p>

                {% if detail.quote %}
           <blockquote class="blockquote">
             <p class="mb-0">{{ detail.quote }}</p>
           </blockquote>
                {% endif %}
               <div class="news_d_footer flex-column flex-sm-row">
                 <a href="#"><span class="align-middle mr-2"><i class="ti-heart"></i></span>Lily and 4 people like this</a>
                 <a class="justify-content-sm-center ml-sm-auto mt-sm-0 mt-2" href="#"><span class="align-middle mr-2"><i class="ti-themify-favicon"></i></span>06 Comments</a>
                 <div class="news_socail ml-sm-auto mt-sm-0 mt-2">
               <a href="#"><i class="fab fa-facebook-f"></i></a>
               <a href="#"><i class="fab fa-twitter"></i></a>
               <a href="#"><i class="fab fa-dribbble"></i></a>
               <a href="#"><i class="fab fa-behance"></i></a>
             </div>
               </div>
              </div>

          

          <div class="navigation-area">
                  <div class="row">
                      <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                          <div class="thumb">
                              <a href="#"><img class="img-fluid" src="img/blog/prev.jpg" alt=""></a>
                          </div>
                          <div class="arrow">
                              <a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
                          </div>

                      </div>
                      <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                          <div class="arrow">
                              <a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
                          </div>
                          <div class="thumb">
                              <a href="#"><img class="img-fluid" src="img/blog/next.jpg" alt=""></a>
                          </div>										
                      </div>									
                  </div>
                </div>


                <div class="comments-area">
                    {% for comment in detail.comments.all %}
                    <div class="comment-list">


                        <div class="single-comment justify-content-between d-flex">
                            <div class="user justify-content-between d-flex">
                                <div class="desc">
                                    <h5><a href="#">{{ comment.user.get_full_name }}</a></h5>

                                    <p class="date">{{ comment.create }} </p>
                                    <p class="comment">
                                        {{ comment.text }}

                                    </p>
                                </div>
                            </div>

                            <div class="reply-btn">
                                    <a href="" class="btn-reply text-uppercase">reply</a>
                            </div>
                        </div>

                    </div>
                    {% endfor %}
                    <div class="comment-list left-padding">
                        <div class="single-comment justify-content-between d-flex">
                            <div class="user justify-content-between d-flex">
                                <div class="thumb">
                                    <img src="img/blog/c2.jpg" alt="">
                                </div>
                                <div class="desc">
                                    <h5><a href="#"> {{ reply.user.get_full_name }}</a></h5>
                                    <p class="date">{{ reply.create }} </p>
                                    <p class="comment">
                                        {{ reply.body }}
                                    </p>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
                    <h4>Leave a Reply</h4>
                    <form method="post">
                    {% csrf_token %}
                    <form action="#/" class="form-contact contact_form" method="post" id="contactForm" novalidate="novalidate">

                        <div class="form-group">
                            <textarea class="form-control different-control w-100" name="text" id="text" cols="30" rows="5" placeholder="Enter Message"></textarea>
                        </div>
                        <div class="form-group text-center text-md-right mt-3">
                            <button type="submit" class="button button--active button-contactForm">Send Message</button>
                        </div>
                    </form>
        </div>

        <!-- Start Blog Post Siddebar -->

{% include 'include/sidebar.html' %}
          </div>
        <!-- End Blog Post Siddebar -->
      </div>
  </section>
  <!--================ End Blog Post Area =================-->

  <!--================ Start Footer Area =================-->
{% endblock %}

blog/templates/blog/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<body>
  <!--================Header Menu Area =================-->

  <!--================Header Menu Area =================-->
  
  <!--================ Hero sm banner start =================-->  
  <section class="mb-30px">
    <div class="container">
      <div class="hero-banner hero-banner--sm">
        <div class="hero-banner__content">
          <h1>Contact Us</h1>
          <nav aria-label="breadcrumb" class="banner-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Contact Us</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
  <!--================ Hero sm banner end =================-->  


  <!-- ================ contact section start ================= -->
  <section class="section-margin--small section-margin">
    <div class="container">
      <div class="d-none d-sm-block mb-5 pb-4">
        <div id="map" style="height: 420px;"></div>
        <script>
          function initMap() {
            var uluru = {lat: -25.363, lng: 131.044};
            var grayStyles = [
              {
                featureType: "all",
                stylers: [
                  { saturation: -90 },
                  { lightness: 50 }
                ]
              },
              {elementType: 'labels.text.fill', stylers: [{color: '#A3A3A3'}]}
            ];
            var map = new google.maps.Map(document.getElementById('map'), {
              center: {lat: -31.197, lng: 150.744},
              zoom: 9,
              styles: grayStyles,
              scrollwheel:  false
            });
          }
          
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
        
      </div>


      <div class="row">
        <div class="col-md-4 col-lg-3 mb-4 mb-md-0">
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>California United States</h3>
              <p>Santa monica bullevard</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-headphone"></i></span>
            <div class="media-body">
              <h3><a href="tel:454545654">00 (440) 9865 562</a></h3>
              <p>Mon to Fri 9am to 6pm</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
              <h3><a href="mailto:support@colorlib.com">support@colorlib.com</a></h3>
              <p>Send us your query anytime!</p>
            </div>
          </div>
        </div>

        <div class="col-md-8 col-lg-9">
          <form action="#/" class="form-contact contact_form" action="contact_process.php" method="post" id="contactForm" novalidate="novalidate">
                {% csrf_token %}
                {{ contact.errors }}

                {{ contact }}
            <div class="form-group text-center text-md-right mt-3">
              <button type="submit" class="button button--active button-contactForm">Send Message</button>
            </div>
          </form>


        </div>
      </div>
    </div>
  </section>
	<!-- ================ contact section end ================= -->

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
{% include 'include/header.html' %}
</head>



  <header class="header_area">
   {% include 'include/header_reference.html' %}
  </header>

{% block content %}

{% endblock %}

  <footer class="footer-area section-padding">
    {% include 'include/footer.html' %}
  </footer>
  <!--================ End Footer Area =================-->

{% include 'include/footer_reference.html' %}

templates/include/footer.html
{% load static %}

      <div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
        <p class="footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
      </div>
    </div>

templates/include/header.html
{% load static %}
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Sensive Blog - Home</title>
	<link rel="icon" href="{% static 'img/Fevicon.png' %}" type="image/png">

  <link rel="stylesheet" href="{% static 'vendors/bootstrap/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/fontawesome/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/themify-icons/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/linericon/style.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">

templates/include/header_reference.html
 {% load static %}
 {% load social_share %}

<div class="main_menu">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container box_1620">
          <!-- Brand and toggle get grouped for better mobile display -->
          <a class="navbar-brand logo_h" href="index.html"><img src="{% static 'img/logo.png' %}" alt=""></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
            <ul class="nav navbar-nav menu_nav justify-content-center">

              <li class="nav-item {% if request.resolver_match.url_name == 'landing' %} active {% endif %}">
                <a class="nav-link" href="{% url 'home:landing' %}">Home</a>
                </li>


              <li class="nav-item {% if request.resolver_match.url_name == 'list' %}active{% endif %} ">
                  <a class="nav-link" href="{% url 'detail:list' %}">Article List</a>
              </li>

                  <li class="nav-item {% if request.resolver_match.url_name == '' %}active{% endif %} ">
                      <a class="nav-link" href="{% url 'detail:list' %}">Blog Details</a>
                  </li>

              <li class="nav-item {% if request.resolver_match.url_name == 'contact' %}active{% endif %} ">
                  <a class="nav-link" href="{% url 'detail:contact' %}">Contact</a></li>
            </ul>
            <ul class="nav  navbar-right navbar-social">
                <li> {% post_to_facebook 'facebook' '   ' 'ti-facebook' %}</li>
                <li> {% post_to_twitter 'twitter' '' ' ' 'ti-twitter' %}</li>
                <li>{% post_to_linkedin 'linkdin' '' %}</li>

            </ul>
          </div>
        </div>
      </nav>
    </div>

templates/include/sidebar.html
{% load static %}

<div class="col-lg-4 sidebar-widgets">
              <div class="widget-wrap">


                <div class="single-sidebar-widget post-category-widget">
                  <h4 class="single-sidebar-widget__title">Catgory</h4>
                    {% for cat in category %}
                  <ul class="cat-list mt-20">
                    <li>
                      <a href="#" class="d-flex justify-content-between">
                        <p> {{ cat.title }} </p>
                      </a>
                    </li>
                  </ul>
                    {% endfor %}
                </div>


                <div class="single-sidebar-widget popular-post-widget">
                  <h4 class="single-sidebar-widget__title">Popular Post</h4>
                  <div class="popular-post-list">
                    <div class="single-post-list">


                        {% for recent in recent_article %}

                      <div class="details mt-20">
                        <a href="{% url 'detail:list' %}">
                          <h6>{{ recent.title }}</h6>
                        </a>
                      </div>
                    </div>

                    <div class="single-post-list">
                      <div class="thumb">
                        <img class="card-img rounded-0" src="{{ recent.img.url }}" alt="">
                        <ul class="thumb-info">
                          <li>{{ recent.auth }}</li>
                          <li>{{ recent.created_at }}</li>
                        </ul>
                      </div>
                        {% endfor %}
                    </div>
                  </div>
                </div>


                </div>
              </div>
            </div>